version: '3.8'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/labs-mongo-colossal-many-football
      - JWT_SECRET=uY7kzlbzqot1thbSa6rhXFmk
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: